# Generated by Django 4.0 on 2021-12-24 08:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('national_id', models.CharField(db_index=True, editable=False, max_length=40, unique=True, default="")),
                ('name', models.CharField(default='', max_length=255)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
