# Generated by Django 4.0 on 2021-12-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='national_id',
            field=models.CharField(db_index=True, editable=False, max_length=40, unique=True),
        ),
    ]
